version: '3'

services:
  php:
    image: 'php:7.2-apache'
    restart: 'unless-stopped'
    volumes: [ './app:/var/www/html/' ]
    depends_on: ['influxdb']
    environment:
      - GAME_USERNAME
      - GAME_PASSWORD
    ports: 
      - '1234:80'

  influxdb:
    image: 'influxdb:1.7.2'
    restart: 'unless-stopped'      
    volumes: [ './influx-data:/var/lib/influxdb' ]
    ports: 
      - '8086:8086'    